### ISSUE TITLE
More buttons for alt?

### ISSUE THREAD

**Issue by xCuubix** [ils94/PyFlyff#12]
Hey, 
just tested the new Profile feature, its great!

Is there any chance to asdd more alt control key buttons or like a chain of commands to send to the alt client?
Intention is to do a rebuff on a one button click.

Cheers

**Comment by ils94** [comment]
> Hey, just tested the new Profile feature, its great!
> 
> Is there any chance to asdd more alt control key buttons or like a chain of commands to send to the alt client? Intention is to do a rebuff on a one button click.
> 
> Cheers

You can map up to 20 buttons

the first button you choose for the main client will be the first button for the alt client as well.

if you want more than one button, just use commas "," to separate the buttons like this:

Main Client: e,q,f1,x
Alt Client: 1,2,3,z

so when you press "e" on main client, it will press "1" in the alt client, same for "q" to "2", "f1" for "3" and so on...

**Comment by xCuubix** [comment]
Oooooh thank u just saw it in the updated client aswell!
