### ISSUE TITLE
Usage on Mac?

### ISSUE THREAD

**Issue by aiverkeith** [ils94/PyFlyff#19]
How to use this on Mac? I don't see any documentation on how to run this on MacBook. I'm happy contribute to the documentation if you can point on how to get started or if it's possible

**Comment by ils94** [comment]
> How to use this on Mac? I don't see any documentation on how to run this on MacBook. I'm happy contribute to the documentation if you can point on how to get started or if it's possible

This is made to run only on Windows, I have no knowledge with Objective C / Swift.

You can install a VM with Windows in your Mac tho.
