### ISSUE TITLE
Profile Customization[QUESTION]

### ISSUE THREAD

**Issue by FelipeCardona95** [ils94/PyFlyff#21]
Hello how are you doing?, great and fantastic tool been using it since I found about it, today I want to ask if its possible to change the name of the existing profiles you have if thats not the case then what about deleting profiles or theres a place where they are stored so I can just go and delete them? if any of the above is not an option I can just install the tool again from 0 to make new profiles as I want haha,(or is that saved in the local outside the tools folder?)

Edit: oh well I found where profiles are, so what you think about the "customization" thing, not really worth the effort?
https://github.com/ils94/PyFlyff/blob/main/PyFlyff.py#L51

**Comment by ils94** [comment]
They are created inside C://PyFlyff

I would recommend just deleting them, if you want to try to rename then, change the folder name to whatever you want and then edit the profile.txt and also change the name of the profile to the same as the folder you changed the name.

**Comment by FelipeCardona95** [comment]
Yes that was exactly what I did, thank you anyway :D great tool
