### ISSUE TITLE
MiniFtool/Alt Control for multiple profiles

### ISSUE THREAD

**Issue by FelipeCardona95** [ils94/PyFlyff#22]
Hey this is mainly to ask if this would be possible to implement on the current tool like make the alt control and the mini Ftool send keys to multiple profiles/windows would be possible to use multiple pofiles for these 2? for example if I want to use my 2 RM at the same time with my another character which is killing?

or this wont be easy to add since you directly use these input exclusively for the selected profile?

this is my fav tool been using it everyday :D

**Comment by ils94** [comment]
> Hey this is mainly to ask if this would be possible to implement on the current tool like make the alt control and the mini Ftool send keys to multiple profiles/windows would be possible to use multiple pofiles for these 2? for example if I want to use my 2 RM at the same time with my another character which is killing?
> 
> or this wont be easy to add since you directly use these input exclusively for the selected profile?
> 
> this is my fav tool been using it everyday :D

You can use mini ftool for one profile and alt control for another profile, having mini ftool and all control for multiple profiles would be tough now because i didn't take it into consideration...

**Comment by FelipeCardona95** [comment]
Yeah but in the case of having 3 profiles at the same time will not have a key repeat/ alt control, I meanly meant to this, why would it be difficult? cause key strokes are directly sent to the windows?
