### ISSUE TITLE
Tools not working

### ISSUE THREAD

**Issue by xCuubix** [ils94/PyFlyff#6]
Hi!
First and formost thank you for your effort!

I managed to set it up on windows and launched the main and the alt windows.
When i want to click on Tool->Mini Ftool or Tools-> Alt control nothing happens.
I dont know what i am doing wrong here :/

**Comment by ils94** [comment]
Did you had a old version of my client and just downloaded the .EXE? I change the icon to a new one, and Tkinter might be going angry saying that "could not find the icon bla bla".

You can fully download the client again from this link: https://github.com/ils94/PyFlyff/releases/download/release/PyFlyff.7z

Or go to the client folder - icons folder and change the name of the icon file from Flyffu to PyFlyff
